version: '3'
services:
    build:
        container_name: nginx
        image: nginx
        build:
            context: .
        volumes:
            - ./:/var/www
        ports:
            - "80:80"
